In [1]:
import numpy as np

### DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray (n dimensional array)
# 1 dimensional, Names: Array, vector || Shape = (1, 4) or (1, n)
a1 = np.array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [6]:
# Multi dimensional, Names: Array, matrix || Shape = (2, 3) or (n, n)
a2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])

# Multi dimensional, Names: Array, matrix || Shape = (2, 3, 3) or (n, n, n)
a3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
])

### Axis || Dimension || Shape (Axis, Axis, ...):
- Axis 0: Row || Vertical (Dimension 0 or d0)
- Axis 1: Column || Horizontal (Dimension 1 or d1)
- Axis n: n Dimension || Depth ((Dimension n or dn)

In [12]:
print(f"a1.shape: {a1.shape}, a2.shape: {a2.shape}, a3.shape: {a3.shape}")
print(f"Dimensions: a1.ndim: {a1.ndim}, a2.ndim: {a2.ndim}, a3.ndim: {a3.ndim}")

a1.shape: (4,), a2.shape: (2, 3), a3.shape: (2, 3, 3)
Dimensions: a1.ndim: 1, a2.ndim: 2, a3.ndim: 3


In [22]:
# data types
print(f"a1.dtype: {a1.dtype}, a2.dtype: {a2.dtype}, a3.dtype: {a3.dtype}")

# element size
print(f"a1.size: {a1.size}, a2.size: {a2.size}, a3.size: {a3.size}")
type(a1), type(a2), type(a3) # all are numpy.ndarray

a1.dtype: int64, a2.dtype: float64, a3.dtype: int64
a1.size: 4, a2.size: 6, a3.size: 18


(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### DataFrame form a Numpy Array:

In [15]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Creating arrays:

In [16]:
sample_array = np.array([1,2,3])

In [19]:
# shift + tab to get docs/prarms
# Return a new array of given shape and type, filled with ones.
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [28]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# ndarray from range
# arange([start,] stop[, step,], dtype=None, *, like=None)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
# random ndarray: randint(low, high=None, size=None, dtype=int)
random_array = np.random.randint(0, 10, (3,3))
random_array

array([[8, 3, 2],
       [6, 0, 6],
       [9, 2, 4]])

In [33]:
# random ndarray: random(size=None)
# Return random floats in the half-open interval [0.0, 1.0)
random_arr_2 = np.random.random((1,2,3))
random_arr_2

array([[[0.92071499, 0.00878512, 0.0702854 ],
        [0.3001116 , 0.53785825, 0.33374222]]])

In [35]:
random_arr_2.shape

(1, 2, 3)

In [37]:
# random ndarray: rand(d0, d1, ..., dn)
# Random values in a given shape.
random_arr_3 = np.random.rand(4,3)
random_arr_3

array([[0.48150425, 0.71911076, 0.25357877],
       [0.79938801, 0.79929176, 0.17519664],
       [0.47801893, 0.6157459 , 0.65698275],
       [0.50829846, 0.28691424, 0.07735197]])

### Seed || Same Random Numbers || Pseudo Random Numbers:

In [40]:
# seed: Pseudo Random Numbers : Non-random random numbers
# Reseed the singleton RandomState instance, so on same seed the numbers are identical
np.random.seed(0)
random_array_4 = np.random.randint(0, 10, (3,4))
random_array_4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [59]:
# np.random.seed(7)
# seed will only once for each underneth random fn
random_array_5 = np.random.randint(0, 10, (3,4))
random_array_5

array([[9, 7, 7, 6],
       [2, 5, 6, 1],
       [9, 3, 4, 0]])

### Viewing arrays and matrices:

In [60]:
# Find unique numbers from a NumPy array
np.unique(random_array_4)

array([0, 2, 3, 4, 5, 6, 7, 9])

In [61]:
# slicing and indexing array
a3 = np.random.randint(10, size=(2,3,4,5))
a3
# count numbers from outer most size (5) to innermost indexes (5 elements) 

array([[[[3, 5, 6, 4, 0],
         [4, 1, 5, 2, 4],
         [8, 7, 5, 7, 5],
         [3, 7, 6, 2, 3]],

        [[1, 1, 8, 4, 2],
         [1, 7, 0, 8, 8],
         [1, 2, 3, 0, 1],
         [1, 5, 5, 6, 0]],

        [[9, 3, 2, 4, 2],
         [8, 4, 9, 0, 0],
         [2, 6, 3, 9, 5],
         [4, 6, 9, 9, 9]]],


       [[[4, 8, 2, 4, 6],
         [5, 3, 5, 2, 6],
         [4, 3, 2, 5, 9],
         [7, 5, 8, 5, 2]],

        [[0, 9, 3, 2, 2],
         [4, 3, 4, 8, 7],
         [0, 2, 7, 8, 8],
         [4, 0, 4, 1, 7]],

        [[4, 9, 0, 1, 0],
         [6, 2, 0, 2, 4],
         [4, 1, 0, 0, 2],
         [3, 7, 6, 9, 3]]]])

In [62]:
a3[:, :, :, :4]

array([[[[3, 5, 6, 4],
         [4, 1, 5, 2],
         [8, 7, 5, 7],
         [3, 7, 6, 2]],

        [[1, 1, 8, 4],
         [1, 7, 0, 8],
         [1, 2, 3, 0],
         [1, 5, 5, 6]],

        [[9, 3, 2, 4],
         [8, 4, 9, 0],
         [2, 6, 3, 9],
         [4, 6, 9, 9]]],


       [[[4, 8, 2, 4],
         [5, 3, 5, 2],
         [4, 3, 2, 5],
         [7, 5, 8, 5]],

        [[0, 9, 3, 2],
         [4, 3, 4, 8],
         [0, 2, 7, 8],
         [4, 0, 4, 1]],

        [[4, 9, 0, 1],
         [6, 2, 0, 2],
         [4, 1, 0, 0],
         [3, 7, 6, 9]]]])

In [63]:
a3[1][0][0]

array([4, 8, 2, 4, 6])

### Manipulate Arrays (ndarrays) & comparing:

In [64]:
### Arithmetic 